### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by ZHANGSHAOKANG** [catalsdevelop/flextracker#2]
I can't download it when I run 'npm i',what's wrong with it?Please tell me why,thanks.

**Comment by carlisliu** [comment]
'npm i ' is used to install the dependencies described in package.json file which this module depends on, not to download this module itself.
And this module is not published to npm repository yet.

**Comment by catalsdevelop** [comment]
hi, @ZHANGSHAOKANG, sorry for my late reply. You need to `git clone` first and then `npm i`. This is not a lib or tool, so I think you need to complete or modify them to match your satisfcation.
